openapi: 3.0.0
info:
  title: Tracking Service API
  version: 1.0.0
paths:
  /track:
    get:
      summary: Get tracking information for an order
      parameters:
        - name: orderId
          in: query
          description: ID of the order to track
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackingResponse'
        '404':
          description: Order not found
        '500':
          description: Internal server error
components:
  schemas:
    TrackingResponse:
      type: object
      properties:
        orderId:
          type: string
        status:
          type: string
        location:
          type: string
        previousLocations:  
          $ref: '#/components/schemas/PreviousLocations'
    PreviousLocations:
      type: array
      items:
        type: object
        properties:
          location:
            type: string
          timestamp:
            type: string